# Generated by Django 4.2.2 on 2023-06-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Choban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choban',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
